# Generated by Django 3.1.7 on 2021-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://i.ibb.co/d400nvn/pp.png'),
        ),
    ]
