# Generated by Django 3.1.7 on 2021-05-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0002_auto_20210506_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(max_length=9999, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(default=None, max_length=250, unique=True),
        ),
    ]
