# Generated by Django 3.1.7 on 2021-04-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0002_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
