# Generated by Django 3.1.7 on 2021-04-29 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typeFiction', '0003_auto_20210428_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='body',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='watchlist',
            field=models.ManyToManyField(default=0, related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=9999)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeFiction.story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='typeFiction.category'),
        ),
    ]
