# Generated by Django 3.1.7 on 2021-05-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0003_auto_20210506_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(max_length=30),
        ),
    ]
