# Generated by Django 3.1.7 on 2021-04-29 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0004_auto_20210429_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='story',
        ),
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='story',
            name='chapters',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='typeFiction.category'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(default=None, max_length=9999),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
