# Generated by Django 3.1.7 on 2021-04-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0005_auto_20210429_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='story',
            name='chapters',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ManyToManyField(to='typeFiction.Story'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(),
        ),
    ]
