# Generated by Django 3.1.7 on 2021-04-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0006_auto_20210429_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='chapters',
            field=models.ManyToManyField(to='typeFiction.Chapter'),
        ),
    ]
