# Generated by Django 3.1.7 on 2021-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0007_auto_20210429_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default=None),
        ),
    ]
