# Generated by Django 3.1.7 on 2021-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeFiction', '0008_auto_20210429_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.URLField(),
        ),
    ]
